### ISSUE TITLE
Vercel deployment

### ISSUE THREAD

**Issue by ajnart** [tuanphungcz/nextjs-notion-blog-starter#1]
I'm looking forward to setting this up as my open notebook deployed on vercel. 
For that I would need to hide keep my secrets locally while also having them on vercel. 
This doesn't seem to be explained in the docs.
 
You should be able to set up a Deploy button 
https://vercel.com/docs/deploy-button
with the correct API keys field and get a super simple deployment setup for new users 

I've went ahead and made a deploy button already : 
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Ftuanphungcz%2Fnextjs-notion-blog-starter&env=NOTION_SECRET,DATABASE_ID&envDescription=Notion%20secret%20API%20key%20&envLink=https%3A%2F%2Fnextjs-notion-blog-starter.vercel.app%2Fblog%2Fdeploy-your-notion-blog-powered-by-nextjs-and-tailwind&project-name=my-notion-blog&repo-name=my-notion-blog)

I would recommend you include it in the readme along with the "Run locally" section. I would open a PR but I'm on mobile at the moment

**Comment by ajnart** [comment]
Nice ! I saw you just did that in your latest commit

**Comment by tuanphungcz** [comment]
@ajnart

yep! thanks for the deploy button, I forgot to ping you. 😄

I'm closing the issue then
