### ISSUE TITLE
Notion Database Connection Error!!   

### ISSUE THREAD

**Issue by muskansingh65553** [tuanphungcz/nextjs-notion-blog-starter#10]
![image](https://github.com/tuanphungcz/nextjs-notion-blog-starter/assets/71725061/ac4c619e-908b-4d03-942c-54554cb646d6)

I added this id but still facing issue
![image](https://github.com/tuanphungcz/nextjs-notion-blog-starter/assets/71725061/dbe19b25-a151-46fa-9829-e685fab44b79)

**Comment by Ultorem** [comment]
Make sure you publish it, upper right corner click share and publish to web

https://i.imgur.com/D7CGnnX.png

**Comment by tuanphungcz** [comment]
hey @muskansingh65553 thanks for bug report. I have reworked the codebase and updated to latest packages, it should be working fine now.
