### ISSUE TITLE
Notion setup link is broken

### ISSUE THREAD

**Issue by ajnart** [tuanphungcz/nextjs-notion-blog-starter#2]
https://nextjs-notion-blog-starter.vercel.app/blog/deploy-your-notion-blog-powered-by-nextjs-and-tailwind#notion-setup
![image](https://user-images.githubusercontent.com/49837342/188331224-cac64416-4b93-4c33-aca8-58b9afbd063a.png)

This link doesn't work

**Comment by tuanphungcz** [comment]
@ajnart Nice catch! I fixed it in the blog and here is the template URL just in case 👉https://www.notion.so/6a05e6e596ac4bc6b591734f5c3d9850. 

Let me then know how your blog is doing!
