### ISSUE TITLE
Guide for the new version?

### ISSUE THREAD

**Issue by animemandir** [tuanphungcz/nextjs-notion-blog-starter#3]
Amazing project ! ✨ i'd like to test this on local or deploy somewhere.
guide on how to deploy [demo.blogfolio.co](https://demo.blogfolio.co/)

**Comment by animemandir** [comment]
How to generate env's for the ne version?
It can generate it's own subdomains too awesome !! 🔥

But it won't work on local without proper env vars right? How to make it work?

**Comment by tuanphungcz** [comment]
hey @animemandir, Thanks for reaching out to me. I decided to revert to the previous version of the blog, which is easier to deploy: https://nextjs-notion-blog-starter.vercel.app/. 

If you be still interested in how to deploy the newer version of the blog, then you need to also deploy this service worker on Cloudflare to make it work:https://www.npmjs.com/package/notion-api-worker. 

Hope this helps and happy holidays! 🎄 :)
