### ISSUE TITLE
Add dark demo

### ISSUE THREAD

**Issue by tuanphungcz** [tuanphungcz/nextjs-notion-blog-starter#6]
Task:
Add dark demo in tailwind

example: https://tailwindcss.com/docs/dark-mode

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by sharmashubam** [comment]
hey @tuanphungcz , I would like to help.

**Comment by tuanphungcz** [comment]
Feel free to take this task @sharmashubam 👍

**Comment by mohitmohlia** [comment]
@sharmashubam any progress on this? @tuanphungcz please assign this to me, I have added the theme functionality. Will raise the PR soon.

**Comment by tuanphungcz** [comment]
@mohitmohlia feel free to open PR for this feature!

**Comment by mohitmohlia** [comment]
@tuanphungcz  hope this PR helps with the dark mode
