### ISSUE TITLE
Serializing issue when setting up project

### ISSUE THREAD

**Issue by mohitmohlia** [tuanphungcz/nextjs-notion-blog-starter#8]
![ss](https://user-images.githubusercontent.com/46368810/219378256-99a6d7c6-1f9a-4063-b1b0-ae68a726a083.jpg)

i had to 
` return {
    props: {
      articles:JSON.parse(JSON.stringify(articles)),
      categories
    },
    revalidate: 30
  };`

**Comment by brian7989** [comment]
I found a very simple fix to this issue. Refer to this [Notion docs](https://developers.notion.com/reference/capabilities). Modify "User Capabilities" to "Read user information without email addresses". Once this permission is granted, it should work.

**Comment by tuanphungcz** [comment]
I've refactored the codebase and updated all dependencies. Everything should be working fine now! 👍
