### ISSUE TITLE
Responsive Issue

### ISSUE THREAD

**Issue by muskansingh65553** [tuanphungcz/nextjs-notion-blog-starter#9]
![image](https://github.com/tuanphungcz/nextjs-notion-blog-starter/assets/71725061/cf23031c-6020-4eb5-86de-c65cd140b539)

**Comment by tuanphungcz** [comment]
I just fixed the responsive issue on blog post 
![image](https://github.com/tuanphungcz/nextjs-notion-blog-starter/assets/16448321/23258460-c93c-4000-9af8-7ed28d74ddcc)

https://github.com/tuanphungcz/nextjs-notion-blog-starter/commit/baf6e9c04c862461e45f3e8822d9c754d0c71881
